---

- hosts: servera
  become: true

  tasks:

    - name: Configuring "Wired connection 1" Connection
      shell: "nmcli con add con-name \"Wired connection 1\" type ethernet ifname SEC_NIC ipv4.method manual ipv4.address 172.25.250.10/24 ipv4.gateway 172.25.250.254 ipv4.dns 172.25.250.220"
