---

- hosts: servera
  become: true

  tasks:

    - name: Reconfigure Firewalld
      shell: "firewall-cmd --remove-port=82/tcp --permanent && firewall-cmd --reload"
      ignore_errors: true

    - name: Reconfiguring SELinux
      shell: "semanage port -d -t http_port_t -p tcp 82"
      ignore_errors: true
    
    - name: Resetting Firewall
      shell: "firewall-cmd --remove-port=82/tcp --permanent && firewall-cmd --reload"
      ignore_errors: true

    - name: Stopping and Removing Apache from the System
      shell: "systemctl disable --now httpd && dnf remove httpd -y"
      ignore_errors: true

    - name: Cleaning Up
      file:
       path: /var/www
       state: absent

