---

- hosts: servera
  become: true

  tasks:

    - name: Installing Extra Packages
      dnf:
        name: httpd,pykickstart
        state: latest
        update_cache: true

    - name: Creating Directory
      file:
        path: "/var/www/html/ks-config"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Configuring Firewall
      shell: "firewall-cmd --add-port=80/tcp --permanent && firewall-cmd --reload"
