---

- hosts: servera
  become: true
  gather_facts: false

  tasks:

    - name: Installing rsync
      shell: "dnf install -y rsync"
    
    - name: Configuring SSH Acces
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "#PermitRootLogin prohibit-password"
        line: "PermitRootLogin yes"
    
    - name: Restarting SSHD Service
      shell: "systemctl restart sshd"

- hosts: serverb
  become: true
  gather_facts: false

  tasks:

    - name: Installing rsync
      shell: "dnf install -y rsync"

    - name: Configuring SSH Acces
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "#PermitRootLogin prohibit-password"
        line: "PermitRootLogin yes"

    - name: Restarting SSHD Service
      shell: "systemctl restart sshd"
